// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todoAPI.Models;

namespace todoAPI.Migrations
{
    [DbContext(typeof(TodoDetailContext))]
    partial class TodoDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("todoAPI.Models.TodoDetail", b =>
                {
                    b.Property<int>("TodoDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TodoDetailId");

                    b.ToTable("TodoDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
